# Generated by Django 6.0.7 on 2026-07-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.PositiveIntegerField(default=0)),
                ("created_at", models.TimeField(auto_now_add=True)),
                ("created_date", models.DateField(auto_now_add=True)),
                ("updated_at", models.TimeField(auto_now=True)),
            ],
        ),
    ]
