# Generated by Django 6.0.7 on 2026-07-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="descriptions",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
