# Generated by Django 6.0.7 on 2026-07-15 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_product_descriptions"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Product",
            new_name="Insta",
        ),
    ]
