# Generated by Django 6.0.7 on 2026-07-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_product_insta"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("comment", models.TextField()),
                ("likes", models.IntegerField(default=0)),
                ("author", models.CharField(max_length=100)),
                ("created_at", models.TimeField(auto_now_add=True)),
                ("created_date", models.DateField(auto_now_add=True)),
                ("updated_at", models.TimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Insta",
        ),
    ]
